[package]
name = "envshare-node"
description = "Untrusted discovery and circuit relay node for Envshare"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[[bin]]
name = "envshare-node"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
libp2p.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

