[package]
name = "cli"
description = "Accountless one-time environment transfer CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[[bin]]
name = "envshare"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
cliclack.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
console.workspace = true
code.workspace = true
app-core.workspace = true
crypto.workspace = true
getrandom.workspace = true
humantime.workspace = true
network.workspace = true
protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zeroize.workspace = true

[lints]
workspace = true

[package.metadata.dist]
changelog = "../../CHANGELOG.md"
display-name = "Envshare"
dist = true
formula = "envshare"
installers = ["shell", "powershell", "homebrew"]

[dev-dependencies]
node = { version = "=0.1.2", path = "../node" }
tempfile.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix.workspace = true
