[package]
name = "testkit"
description = "Integration-test support for Envshare"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
code.workspace = true
app-core.workspace = true
crypto.workspace = true
humantime.workspace = true
network.workspace = true
node = { version = "=0.1.1", path = "../node" }
protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
