[package]
name = "network"
description = "Libp2p networking for Envshare clients"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures.workspace = true
libp2p.workspace = true
protocol.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
protocol.workspace = true

[lints]
workspace = true
